Vagrant::Config.run do |config|
config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifests_file = "default.pp"
    end
config.vm.box = "lucid32"
config.vm.forward_port 80, 3000
end
